In [1]:
import tensorflow as tf

In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b
print(hypothesis)

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

Tensor("add_2:0", dtype=float32)
0 Cost:  36812.957 
Prediction:
 [-20.668022 -18.793524 -21.749792 -22.577562 -13.69076 ]
10 Cost:  1.8682324 
Prediction:
 [149.06087 185.20102 179.25314 196.3088  141.90463]
20 Cost:  1.5265341 
Prediction:
 [149.57808 185.81573 179.86247 196.97156 142.37244]
30 Cost:  1.5218719 
Prediction:
 [149.5833  185.81512 179.86548 196.97408 142.3709 ]
40 Cost:  1.51721 
Prediction:
 [149.58699 185.81267 179.86668 196.9746  142.36797]
50 Cost:  1.5125824 
Prediction:
 [149.59064 185.8102  179.86783 196.97507 142.36502]
60 Cost:  1.5079731 
Prediction:
 [149.59428 185.80772 179.869   196.97556 142.36209]
70 Cost:  1.5033967 
Prediction:
 [149.59792 185.80527 179.87015 196.97604 142.35916]
80 Cost:  1.498833 
Prediction:
 [149.60155 185.80283 179.8713  196.97652 142.35625]
90 Cost:  1.4943054 
Prediction:
 [149.60515 185.80037 179.87245 196.97699 142.35333]
100 Cost:  1.4897945 
Prediction:
 [149.60875 185.79793 179.8736  196.97746 142.35042]
110 Cost:  1.485289

In [3]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  556.57294 
Prediction:
 [[135.73634]
 [156.39429]
 [157.65477]
 [169.71692]
 [119.41766]]
10 Cost:  10.236613 
Prediction:
 [[156.39996]
 [181.25371]
 [182.13701]
 [196.37906]
 [138.38362]]
20 Cost:  10.17789 
Prediction:
 [[156.45018]
 [181.33734]
 [182.20732]
 [196.4572 ]
 [138.4519 ]]
30 Cost:  10.124505 
Prediction:
 [[156.43806]
 [181.34596]
 [182.20372]
 [196.45488]
 [138.46294]]
40 Cost:  10.071421 
Prediction:
 [[156.4258 ]
 [181.35434]
 [182.19995]
 [196.45235]
 [138.47379]]
50 Cost:  10.01854 
Prediction:
 [[156.41356]
 [181.36273]
 [182.19617]
 [196.4498 ]
 [138.4846 ]]
60 Cost:  9.966006 
Prediction:
 [[156.40135]
 [181.37106]
 [182.1924 ]
 [196.44728]
 [138.49539]]
70 Cost:  9.913761 
Prediction:
 [[156.38919]
 [181.3794 ]
 [182.18866]
 [196.44475]
 [138.50615]]
80 Cost:  9.861791 
Prediction:
 [[156.37704]
 [181.38766]
 [182.18489]
 [196.44223]
 [138.51688]]
90 Cost:  9.8101 
Prediction:
 [[156.36496]
 [181.39598]
 [182.18118]
 [196.43973]
 [138.52757]]
100 Cost: